languageCode = "en-us"
title = "Dimension"
baseurl = "http://example.org/"
theme = "dimension"

[params]
  title = "Catalina Vajiac"
  description = "David claims to use nano just to annoy me"
  logo = "fa-diamond"
  copyright = "Untitled"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/catvajiac"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/catvajiac/"
